// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.Paraphrase
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("original")]
        public string Original { get; set; }

        [JsonProperty("paraphrased")]
        public string Paraphrased { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("originalWords")]
        public long OriginalWords { get; set; }

        [JsonProperty("paraphrasedWords")]
        public long ParaphrasedWords { get; set; }
    }
}
